name: planning_poker_clone
description: planning_poker_clone
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
