name: Gh-Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - run: flutter build web --dart-define-from-file=env.prd.json
      
      - uses: subosito/flutter-action@v1
        with:
          baseHref: /planning_poker_clone/

      - name: Publish Gh-Page
      - uses: bluefireteam/flutter-gh-pages@v7

      
